"""Add worldcup count fields to users

Revision ID: 2fe7bd3a35d8
Revises: 5459046396b1
Create Date: 2025-11-04 08:35:09.892396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fe7bd3a35d8'
down_revision: Union[str, Sequence[str], None] = '5459046396b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('worldcup_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('monthly_worldcup_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_reset_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_reset_at')
    op.drop_column('users', 'monthly_worldcup_count')
    op.drop_column('users', 'worldcup_count')
    # ### end Alembic commands ###
