"""Add OAuth fields to users

Revision ID: 6f03b45deb06
Revises: 6976e442f00c
Create Date: 2025-11-04 15:09:58.294979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f03b45deb06'
down_revision: Union[str, Sequence[str], None] = '6976e442f00c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_matches_worldcup_id'), table_name='matches')
    op.drop_index(op.f('idx_photos_created_at'), table_name='photos')
    op.drop_index(op.f('idx_photos_user_id'), table_name='photos')
    op.drop_index(op.f('idx_shares_worldcup_id'), table_name='shares')
    op.add_column('users', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('provider_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_image', sa.String(), nullable=True))
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_worldcups_created_at'), table_name='worldcups')
    op.drop_index(op.f('idx_worldcups_status'), table_name='worldcups')
    op.drop_index(op.f('idx_worldcups_user_id'), table_name='worldcups')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_worldcups_user_id'), 'worldcups', ['user_id'], unique=False)
    op.create_index(op.f('idx_worldcups_status'), 'worldcups', ['status'], unique=False)
    op.create_index(op.f('idx_worldcups_created_at'), 'worldcups', ['created_at'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_column('users', 'profile_image')
    op.drop_column('users', 'provider_id')
    op.drop_column('users', 'provider')
    op.create_index(op.f('idx_shares_worldcup_id'), 'shares', ['worldcup_id'], unique=False)
    op.create_index(op.f('idx_photos_user_id'), 'photos', ['user_id'], unique=False)
    op.create_index(op.f('idx_photos_created_at'), 'photos', ['uploaded_at'], unique=False)
    op.create_index(op.f('idx_matches_worldcup_id'), 'matches', ['worldcup_id'], unique=False)
    # ### end Alembic commands ###
