"""Create worldcups and matches tables

Revision ID: f010124f57e8
Revises: 7be1c1887109
Create Date: 2025-11-02 17:36:53.855749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f010124f57e8'
down_revision: Union[str, Sequence[str], None] = '7be1c1887109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worldcups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('round_type', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', name='worldcupstatus'), nullable=True),
    sa.Column('winner_photo_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_photo_id'], ['photos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('worldcup_id', sa.String(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('match_order', sa.Integer(), nullable=False),
    sa.Column('photo_a_id', sa.String(), nullable=False),
    sa.Column('photo_b_id', sa.String(), nullable=False),
    sa.Column('winner_photo_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['photo_a_id'], ['photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_b_id'], ['photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_photo_id'], ['photos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['worldcup_id'], ['worldcups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('worldcups')
    # ### end Alembic commands ###
